version: "3.7"
services:
  airflow:
    image: airflowbook/airflow:latest
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_CONN_MOVIELENS: http://airflow:airflow@movielens
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags
    depends_on:
      - movielens
  movielens:
    build: api
    image: airflowbook/movielens-api
    ports:
      - "5000:5000"
    networks:
      - airflow

networks:
  airflow:
