version: "3.7"
services:
  events_api:
    build: ./api
    image: manning-airflow-events-api:latest
    ports:
      - "5000:5000"
    networks:
      - airflow
  airflow:
    build: ../../docker
    image: manning-airflow:latest
    ports:
      - "8080:8080"
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags
      - ./data:/data

networks:
  airflow:
