version: '3'
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow:
    build: ../../docker
    image: manning-airflow:latest
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=10
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/root/airflow/dags
    working_dir: /root/airflow
