version: "3.7"
services:
  airflow:
    build: ../../docker
    image: manning-airflow:latest
    ports:
      - "8080:8080"
    environment:
      MOVIELENS_USER: airflow
      MOVIELENS_PASSWORD: airflow
      MOVIELENS_HOST: http://movielens:80
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - movielens
  movielens:
    build: docker/api
    image: airflowbook/movielens-api
    ports:
      - "5000:5000"
    networks:
      - airflow
    environment:
      API_USER: airflow
      API_PASSWORD: airflow

networks:
  airflow:
