
build: build-api build-ranking build-api

build-fetch:
	docker build -t jrderuiter/movielens-fetch docker/movielens-fetch

build-ranking:
	docker build -t jrderuiter/movielens-rank docker/movielens-rank

build-api:
	docker build -t jrderuiter/movielens-api docker/movielens-api
