name: DAG integrity tests

on: [push]
#  push:
#    paths:
#      - "dags/**/*.py"

jobs:
  dag_integrity_test:
    name: DAG integrity tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependencies
        run: pip install apache-airflow pytest

      - name: Test DAG integrity
        run: pytest tests/
